# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Run main command
Type "gh start 'Add a demo animation to README'"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Allow to finish and show output.
Sleep 5s

# Select branch name
Enter

# Allow to finish and show output.
Sleep 15s
