#!/usr/bin/env bash
set -e

# Determine if an executable is in the PATH
if ! type -p ruby >/dev/null; then
  echo "Ruby not found on the system" >&2
  exit 1
fi

if ! type -p bundle >/dev/null; then
  echo "Bundler not found on the system" >&2
  exit 1
fi

# Run bundler/script from extension directory
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
gemfile=$parent_path/Gemfile

BUNDLE_GEMFILE="$gemfile" bundle --quiet && BUNDLE_GEMFILE="$gemfile" bundle exec ruby "$parent_path"/main.rb "$@"
